[tool.poetry]
name = "nba-elt-dashboard"
version = "1.0.10"
description = "NBA Dashboard Project"
authors = ["jyablonski9 <jyablonski9@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
dash = "^2.14.0"
psycopg2-binary = "^2.9.9"
sqlalchemy = "^2.0.22"
pandas = "^2.1.1"
pyyaml = "^6.0.1"
dash-bootstrap-components = "^1.5.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
dash = { extras = ["testing"], version = "^2.14.1" }
coveralls = "^3.3.1"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"
black = "^23.10.0"
ruff = "^0.1.1"


[tool.ruff]
line-length = 100


[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
testpaths = ["tests"]
markers = [
    "wip: work in progress",
    "infrastructure: mocks for dummy data (sql db, http endpoint etc)",
]
addopts = "-v"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
