FROM python:3.12-slim AS base

ENV POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_NO_INTERACTION=1

FROM base AS python-deps

COPY docker/install_packages.sh ./
COPY pyproject.toml poetry.lock ./

RUN ./install_packages.sh && \
    pip install poetry && \
    poetry install --with test

FROM base AS runtime

COPY --from=python-deps /.venv /.venv

ENV PATH="/.venv/bin:$PATH"

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

COPY config.yaml .
COPY src/ src/
COPY static/ static/

EXPOSE 9000

CMD ["python", "-m", "src.server"]