services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=nba_dashboard_user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ${PWD}/docker/postgres_bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
    networks:
      - dashboard_network

  dash_app_test_runner:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        INSTALL_DEV_DEPENDENCIES: "true"
    image: nba_elt_dashboard_local_test
    environment:
      - IP=postgres
      - RDS_USER=nba_dashboard_user
      - RDS_PW=postgres
      - RDS_DB=postgres
      - RDS_SCHEMA=marts
      - ENV_TYPE=docker_dev
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - postgres
    networks:
      - dashboard_network
    links:
      - postgres:postgres
    volumes:
      - ${PWD}/src/:/home/appuser/src
      - ${PWD}/static/:/home/appuser/static
      - ${PWD}/config.yaml:/home/appuser/config.yaml
      - ${PWD}/tests/:/home/appuser/tests
      - ${PWD}/coverage.xml:/home/appuser/coverage.xml # New line for coverage volume
    command: python3 -m pytest --cov-report term --cov-report xml:coverage_report.xml --cov=src --color=yes

networks:
  dashboard_network:
