name: Deploy Pipeline

on:
  push:
    branches:
      - master

env:
  IAM_ROLE: ${{ secrets.IAM_ROLE_ECR }}
  AWS_REGION: "us-east-1"
  ECR_REPO: ${{ secrets.ECR_REPO }}
  IAM_ROLE_SESSION: "nba-elt-dashboard-cd"
  IMAGE_NAME: "nba_elt_pipeline_dashboard"
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}

permissions:
  id-token: write
  contents: read

jobs:
  build_image:
    name: Deploy Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and Push Docker Image to ECR
        uses: jyablonski/actions/deploy@v1
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          ecr-repo: ${{ env.ECR_REPO }}
          image-name: ${{ env.IMAGE_NAME }}
          dockerfile: docker/Dockerfile
          context: .

      - name: Cycle ECS Service
        env:
          ECS_CLUSTER: ${{ env.ECS_CLUSTER }}
          ECS_SERVICE: ${{ env.ECS_SERVICE }}
        run: |
          task_list=$(aws ecs list-tasks --cluster $ECS_CLUSTER --service-name $ECS_SERVICE)
          first_task=$(echo "$task_list" | jq -r '.taskArns[0]')
          aws ecs stop-task --cluster $ECS_CLUSTER --task $first_task
