name: Deploy to GCP VM

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_gcp_vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

      - name: Run deployment script on GCP VM
        run: bash .github/scripts/gcp_vm_update.sh
        env:
          GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
