name: Test Pipeline

on:
  pull_request:


jobs:
  pytest_build:
    name: Test Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          make test
