name: Test Pipeline

on:
  pull_request:

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.6.1"


jobs:
  pytest_build:
    name: Test Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          make test
