name: Deploy Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

      - name: Run deployment script on GCP VM
        run: bash .github/scripts/vm_deploy.sh
        env:
          GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
          GIT_COMMIT: ${{ github.sha }}

  notify:
    needs: [deploy]
    if: always() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Slack Alert
        uses: jyablonski/actions/alert@v1
        with:
          status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          custom_message: "Common Modules Package"
